// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package me.leoyuu.proto;

public final class BasePackets {
  private BasePackets() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PacketType}
   */
  public enum PacketType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AppReverseMsg = 0;</code>
     */
    AppReverseMsg(0),
    /**
     * <code>AppSystemMsg = 1;</code>
     */
    AppSystemMsg(1),
    /**
     * <code>AppChatMsg = 2;</code>
     */
    AppChatMsg(2),
    /**
     * <code>AppUserMsg = 3;</code>
     */
    AppUserMsg(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AppReverseMsg = 0;</code>
     */
    public static final int AppReverseMsg_VALUE = 0;
    /**
     * <code>AppSystemMsg = 1;</code>
     */
    public static final int AppSystemMsg_VALUE = 1;
    /**
     * <code>AppChatMsg = 2;</code>
     */
    public static final int AppChatMsg_VALUE = 2;
    /**
     * <code>AppUserMsg = 3;</code>
     */
    public static final int AppUserMsg_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketType valueOf(int value) {
      return forNumber(value);
    }

    public static PacketType forNumber(int value) {
      switch (value) {
        case 0: return AppReverseMsg;
        case 1: return AppSystemMsg;
        case 2: return AppChatMsg;
        case 3: return AppUserMsg;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PacketType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
            public PacketType findValueByNumber(int number) {
              return PacketType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return me.leoyuu.proto.BasePackets.getDescriptor().getEnumTypes().get(0);
    }

    private static final PacketType[] VALUES = values();

    public static PacketType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PacketType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PacketType)
  }

  public interface PacketContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PacketContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .SysMsg sysMsg = 1;</code>
     */
    boolean hasSysMsg();
    /**
     * <code>optional .SysMsg sysMsg = 1;</code>
     */
    me.leoyuu.proto.SystemPackets.SysMsg getSysMsg();
    /**
     * <code>optional .SysMsg sysMsg = 1;</code>
     */
    me.leoyuu.proto.SystemPackets.SysMsgOrBuilder getSysMsgOrBuilder();

    /**
     * <code>optional .ChatMsg chatMsg = 2;</code>
     */
    boolean hasChatMsg();
    /**
     * <code>optional .ChatMsg chatMsg = 2;</code>
     */
    me.leoyuu.proto.ChatPackets.ChatMsg getChatMsg();
    /**
     * <code>optional .ChatMsg chatMsg = 2;</code>
     */
    me.leoyuu.proto.ChatPackets.ChatMsgOrBuilder getChatMsgOrBuilder();

    /**
     * <code>optional .UserMsg userMsg = 3;</code>
     */
    boolean hasUserMsg();
    /**
     * <code>optional .UserMsg userMsg = 3;</code>
     */
    me.leoyuu.proto.UserPackets.UserMsg getUserMsg();
    /**
     * <code>optional .UserMsg userMsg = 3;</code>
     */
    me.leoyuu.proto.UserPackets.UserMsgOrBuilder getUserMsgOrBuilder();
  }
  /**
   * Protobuf type {@code PacketContent}
   */
  public  static final class PacketContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PacketContent)
      PacketContentOrBuilder {
    // Use PacketContent.newBuilder() to construct.
    private PacketContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketContent() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PacketContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              me.leoyuu.proto.SystemPackets.SysMsg.Builder subBuilder = null;
              if (sysMsg_ != null) {
                subBuilder = sysMsg_.toBuilder();
              }
              sysMsg_ = input.readMessage(me.leoyuu.proto.SystemPackets.SysMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sysMsg_);
                sysMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              me.leoyuu.proto.ChatPackets.ChatMsg.Builder subBuilder = null;
              if (chatMsg_ != null) {
                subBuilder = chatMsg_.toBuilder();
              }
              chatMsg_ = input.readMessage(me.leoyuu.proto.ChatPackets.ChatMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatMsg_);
                chatMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              me.leoyuu.proto.UserPackets.UserMsg.Builder subBuilder = null;
              if (userMsg_ != null) {
                subBuilder = userMsg_.toBuilder();
              }
              userMsg_ = input.readMessage(me.leoyuu.proto.UserPackets.UserMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userMsg_);
                userMsg_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.leoyuu.proto.BasePackets.internal_static_PacketContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.leoyuu.proto.BasePackets.internal_static_PacketContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.leoyuu.proto.BasePackets.PacketContent.class, me.leoyuu.proto.BasePackets.PacketContent.Builder.class);
    }

    public static final int SYSMSG_FIELD_NUMBER = 1;
    private me.leoyuu.proto.SystemPackets.SysMsg sysMsg_;
    /**
     * <code>optional .SysMsg sysMsg = 1;</code>
     */
    public boolean hasSysMsg() {
      return sysMsg_ != null;
    }
    /**
     * <code>optional .SysMsg sysMsg = 1;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysMsg getSysMsg() {
      return sysMsg_ == null ? me.leoyuu.proto.SystemPackets.SysMsg.getDefaultInstance() : sysMsg_;
    }
    /**
     * <code>optional .SysMsg sysMsg = 1;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysMsgOrBuilder getSysMsgOrBuilder() {
      return getSysMsg();
    }

    public static final int CHATMSG_FIELD_NUMBER = 2;
    private me.leoyuu.proto.ChatPackets.ChatMsg chatMsg_;
    /**
     * <code>optional .ChatMsg chatMsg = 2;</code>
     */
    public boolean hasChatMsg() {
      return chatMsg_ != null;
    }
    /**
     * <code>optional .ChatMsg chatMsg = 2;</code>
     */
    public me.leoyuu.proto.ChatPackets.ChatMsg getChatMsg() {
      return chatMsg_ == null ? me.leoyuu.proto.ChatPackets.ChatMsg.getDefaultInstance() : chatMsg_;
    }
    /**
     * <code>optional .ChatMsg chatMsg = 2;</code>
     */
    public me.leoyuu.proto.ChatPackets.ChatMsgOrBuilder getChatMsgOrBuilder() {
      return getChatMsg();
    }

    public static final int USERMSG_FIELD_NUMBER = 3;
    private me.leoyuu.proto.UserPackets.UserMsg userMsg_;
    /**
     * <code>optional .UserMsg userMsg = 3;</code>
     */
    public boolean hasUserMsg() {
      return userMsg_ != null;
    }
    /**
     * <code>optional .UserMsg userMsg = 3;</code>
     */
    public me.leoyuu.proto.UserPackets.UserMsg getUserMsg() {
      return userMsg_ == null ? me.leoyuu.proto.UserPackets.UserMsg.getDefaultInstance() : userMsg_;
    }
    /**
     * <code>optional .UserMsg userMsg = 3;</code>
     */
    public me.leoyuu.proto.UserPackets.UserMsgOrBuilder getUserMsgOrBuilder() {
      return getUserMsg();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sysMsg_ != null) {
        output.writeMessage(1, getSysMsg());
      }
      if (chatMsg_ != null) {
        output.writeMessage(2, getChatMsg());
      }
      if (userMsg_ != null) {
        output.writeMessage(3, getUserMsg());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sysMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSysMsg());
      }
      if (chatMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getChatMsg());
      }
      if (userMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUserMsg());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.leoyuu.proto.BasePackets.PacketContent)) {
        return super.equals(obj);
      }
      me.leoyuu.proto.BasePackets.PacketContent other = (me.leoyuu.proto.BasePackets.PacketContent) obj;

      boolean result = true;
      result = result && (hasSysMsg() == other.hasSysMsg());
      if (hasSysMsg()) {
        result = result && getSysMsg()
            .equals(other.getSysMsg());
      }
      result = result && (hasChatMsg() == other.hasChatMsg());
      if (hasChatMsg()) {
        result = result && getChatMsg()
            .equals(other.getChatMsg());
      }
      result = result && (hasUserMsg() == other.hasUserMsg());
      if (hasUserMsg()) {
        result = result && getUserMsg()
            .equals(other.getUserMsg());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSysMsg()) {
        hash = (37 * hash) + SYSMSG_FIELD_NUMBER;
        hash = (53 * hash) + getSysMsg().hashCode();
      }
      if (hasChatMsg()) {
        hash = (37 * hash) + CHATMSG_FIELD_NUMBER;
        hash = (53 * hash) + getChatMsg().hashCode();
      }
      if (hasUserMsg()) {
        hash = (37 * hash) + USERMSG_FIELD_NUMBER;
        hash = (53 * hash) + getUserMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.BasePackets.PacketContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.leoyuu.proto.BasePackets.PacketContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PacketContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PacketContent)
        me.leoyuu.proto.BasePackets.PacketContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.leoyuu.proto.BasePackets.internal_static_PacketContent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.leoyuu.proto.BasePackets.internal_static_PacketContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.leoyuu.proto.BasePackets.PacketContent.class, me.leoyuu.proto.BasePackets.PacketContent.Builder.class);
      }

      // Construct using me.leoyuu.proto.BasePackets.PacketContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (sysMsgBuilder_ == null) {
          sysMsg_ = null;
        } else {
          sysMsg_ = null;
          sysMsgBuilder_ = null;
        }
        if (chatMsgBuilder_ == null) {
          chatMsg_ = null;
        } else {
          chatMsg_ = null;
          chatMsgBuilder_ = null;
        }
        if (userMsgBuilder_ == null) {
          userMsg_ = null;
        } else {
          userMsg_ = null;
          userMsgBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.leoyuu.proto.BasePackets.internal_static_PacketContent_descriptor;
      }

      public me.leoyuu.proto.BasePackets.PacketContent getDefaultInstanceForType() {
        return me.leoyuu.proto.BasePackets.PacketContent.getDefaultInstance();
      }

      public me.leoyuu.proto.BasePackets.PacketContent build() {
        me.leoyuu.proto.BasePackets.PacketContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.leoyuu.proto.BasePackets.PacketContent buildPartial() {
        me.leoyuu.proto.BasePackets.PacketContent result = new me.leoyuu.proto.BasePackets.PacketContent(this);
        if (sysMsgBuilder_ == null) {
          result.sysMsg_ = sysMsg_;
        } else {
          result.sysMsg_ = sysMsgBuilder_.build();
        }
        if (chatMsgBuilder_ == null) {
          result.chatMsg_ = chatMsg_;
        } else {
          result.chatMsg_ = chatMsgBuilder_.build();
        }
        if (userMsgBuilder_ == null) {
          result.userMsg_ = userMsg_;
        } else {
          result.userMsg_ = userMsgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.leoyuu.proto.BasePackets.PacketContent) {
          return mergeFrom((me.leoyuu.proto.BasePackets.PacketContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.leoyuu.proto.BasePackets.PacketContent other) {
        if (other == me.leoyuu.proto.BasePackets.PacketContent.getDefaultInstance()) return this;
        if (other.hasSysMsg()) {
          mergeSysMsg(other.getSysMsg());
        }
        if (other.hasChatMsg()) {
          mergeChatMsg(other.getChatMsg());
        }
        if (other.hasUserMsg()) {
          mergeUserMsg(other.getUserMsg());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.leoyuu.proto.BasePackets.PacketContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.leoyuu.proto.BasePackets.PacketContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private me.leoyuu.proto.SystemPackets.SysMsg sysMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysMsg, me.leoyuu.proto.SystemPackets.SysMsg.Builder, me.leoyuu.proto.SystemPackets.SysMsgOrBuilder> sysMsgBuilder_;
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public boolean hasSysMsg() {
        return sysMsgBuilder_ != null || sysMsg_ != null;
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysMsg getSysMsg() {
        if (sysMsgBuilder_ == null) {
          return sysMsg_ == null ? me.leoyuu.proto.SystemPackets.SysMsg.getDefaultInstance() : sysMsg_;
        } else {
          return sysMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public Builder setSysMsg(me.leoyuu.proto.SystemPackets.SysMsg value) {
        if (sysMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sysMsg_ = value;
          onChanged();
        } else {
          sysMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public Builder setSysMsg(
          me.leoyuu.proto.SystemPackets.SysMsg.Builder builderForValue) {
        if (sysMsgBuilder_ == null) {
          sysMsg_ = builderForValue.build();
          onChanged();
        } else {
          sysMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public Builder mergeSysMsg(me.leoyuu.proto.SystemPackets.SysMsg value) {
        if (sysMsgBuilder_ == null) {
          if (sysMsg_ != null) {
            sysMsg_ =
              me.leoyuu.proto.SystemPackets.SysMsg.newBuilder(sysMsg_).mergeFrom(value).buildPartial();
          } else {
            sysMsg_ = value;
          }
          onChanged();
        } else {
          sysMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public Builder clearSysMsg() {
        if (sysMsgBuilder_ == null) {
          sysMsg_ = null;
          onChanged();
        } else {
          sysMsg_ = null;
          sysMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysMsg.Builder getSysMsgBuilder() {
        
        onChanged();
        return getSysMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysMsgOrBuilder getSysMsgOrBuilder() {
        if (sysMsgBuilder_ != null) {
          return sysMsgBuilder_.getMessageOrBuilder();
        } else {
          return sysMsg_ == null ?
              me.leoyuu.proto.SystemPackets.SysMsg.getDefaultInstance() : sysMsg_;
        }
      }
      /**
       * <code>optional .SysMsg sysMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysMsg, me.leoyuu.proto.SystemPackets.SysMsg.Builder, me.leoyuu.proto.SystemPackets.SysMsgOrBuilder> 
          getSysMsgFieldBuilder() {
        if (sysMsgBuilder_ == null) {
          sysMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.leoyuu.proto.SystemPackets.SysMsg, me.leoyuu.proto.SystemPackets.SysMsg.Builder, me.leoyuu.proto.SystemPackets.SysMsgOrBuilder>(
                  getSysMsg(),
                  getParentForChildren(),
                  isClean());
          sysMsg_ = null;
        }
        return sysMsgBuilder_;
      }

      private me.leoyuu.proto.ChatPackets.ChatMsg chatMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.ChatPackets.ChatMsg, me.leoyuu.proto.ChatPackets.ChatMsg.Builder, me.leoyuu.proto.ChatPackets.ChatMsgOrBuilder> chatMsgBuilder_;
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public boolean hasChatMsg() {
        return chatMsgBuilder_ != null || chatMsg_ != null;
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public me.leoyuu.proto.ChatPackets.ChatMsg getChatMsg() {
        if (chatMsgBuilder_ == null) {
          return chatMsg_ == null ? me.leoyuu.proto.ChatPackets.ChatMsg.getDefaultInstance() : chatMsg_;
        } else {
          return chatMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public Builder setChatMsg(me.leoyuu.proto.ChatPackets.ChatMsg value) {
        if (chatMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatMsg_ = value;
          onChanged();
        } else {
          chatMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public Builder setChatMsg(
          me.leoyuu.proto.ChatPackets.ChatMsg.Builder builderForValue) {
        if (chatMsgBuilder_ == null) {
          chatMsg_ = builderForValue.build();
          onChanged();
        } else {
          chatMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public Builder mergeChatMsg(me.leoyuu.proto.ChatPackets.ChatMsg value) {
        if (chatMsgBuilder_ == null) {
          if (chatMsg_ != null) {
            chatMsg_ =
              me.leoyuu.proto.ChatPackets.ChatMsg.newBuilder(chatMsg_).mergeFrom(value).buildPartial();
          } else {
            chatMsg_ = value;
          }
          onChanged();
        } else {
          chatMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public Builder clearChatMsg() {
        if (chatMsgBuilder_ == null) {
          chatMsg_ = null;
          onChanged();
        } else {
          chatMsg_ = null;
          chatMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public me.leoyuu.proto.ChatPackets.ChatMsg.Builder getChatMsgBuilder() {
        
        onChanged();
        return getChatMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      public me.leoyuu.proto.ChatPackets.ChatMsgOrBuilder getChatMsgOrBuilder() {
        if (chatMsgBuilder_ != null) {
          return chatMsgBuilder_.getMessageOrBuilder();
        } else {
          return chatMsg_ == null ?
              me.leoyuu.proto.ChatPackets.ChatMsg.getDefaultInstance() : chatMsg_;
        }
      }
      /**
       * <code>optional .ChatMsg chatMsg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.ChatPackets.ChatMsg, me.leoyuu.proto.ChatPackets.ChatMsg.Builder, me.leoyuu.proto.ChatPackets.ChatMsgOrBuilder> 
          getChatMsgFieldBuilder() {
        if (chatMsgBuilder_ == null) {
          chatMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.leoyuu.proto.ChatPackets.ChatMsg, me.leoyuu.proto.ChatPackets.ChatMsg.Builder, me.leoyuu.proto.ChatPackets.ChatMsgOrBuilder>(
                  getChatMsg(),
                  getParentForChildren(),
                  isClean());
          chatMsg_ = null;
        }
        return chatMsgBuilder_;
      }

      private me.leoyuu.proto.UserPackets.UserMsg userMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.UserPackets.UserMsg, me.leoyuu.proto.UserPackets.UserMsg.Builder, me.leoyuu.proto.UserPackets.UserMsgOrBuilder> userMsgBuilder_;
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public boolean hasUserMsg() {
        return userMsgBuilder_ != null || userMsg_ != null;
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public me.leoyuu.proto.UserPackets.UserMsg getUserMsg() {
        if (userMsgBuilder_ == null) {
          return userMsg_ == null ? me.leoyuu.proto.UserPackets.UserMsg.getDefaultInstance() : userMsg_;
        } else {
          return userMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public Builder setUserMsg(me.leoyuu.proto.UserPackets.UserMsg value) {
        if (userMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userMsg_ = value;
          onChanged();
        } else {
          userMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public Builder setUserMsg(
          me.leoyuu.proto.UserPackets.UserMsg.Builder builderForValue) {
        if (userMsgBuilder_ == null) {
          userMsg_ = builderForValue.build();
          onChanged();
        } else {
          userMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public Builder mergeUserMsg(me.leoyuu.proto.UserPackets.UserMsg value) {
        if (userMsgBuilder_ == null) {
          if (userMsg_ != null) {
            userMsg_ =
              me.leoyuu.proto.UserPackets.UserMsg.newBuilder(userMsg_).mergeFrom(value).buildPartial();
          } else {
            userMsg_ = value;
          }
          onChanged();
        } else {
          userMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public Builder clearUserMsg() {
        if (userMsgBuilder_ == null) {
          userMsg_ = null;
          onChanged();
        } else {
          userMsg_ = null;
          userMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public me.leoyuu.proto.UserPackets.UserMsg.Builder getUserMsgBuilder() {
        
        onChanged();
        return getUserMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      public me.leoyuu.proto.UserPackets.UserMsgOrBuilder getUserMsgOrBuilder() {
        if (userMsgBuilder_ != null) {
          return userMsgBuilder_.getMessageOrBuilder();
        } else {
          return userMsg_ == null ?
              me.leoyuu.proto.UserPackets.UserMsg.getDefaultInstance() : userMsg_;
        }
      }
      /**
       * <code>optional .UserMsg userMsg = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.UserPackets.UserMsg, me.leoyuu.proto.UserPackets.UserMsg.Builder, me.leoyuu.proto.UserPackets.UserMsgOrBuilder> 
          getUserMsgFieldBuilder() {
        if (userMsgBuilder_ == null) {
          userMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.leoyuu.proto.UserPackets.UserMsg, me.leoyuu.proto.UserPackets.UserMsg.Builder, me.leoyuu.proto.UserPackets.UserMsgOrBuilder>(
                  getUserMsg(),
                  getParentForChildren(),
                  isClean());
          userMsg_ = null;
        }
        return userMsgBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PacketContent)
    }

    // @@protoc_insertion_point(class_scope:PacketContent)
    private static final me.leoyuu.proto.BasePackets.PacketContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.leoyuu.proto.BasePackets.PacketContent();
    }

    public static me.leoyuu.proto.BasePackets.PacketContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PacketContent>
        PARSER = new com.google.protobuf.AbstractParser<PacketContent>() {
      public PacketContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PacketContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketContent> getParserForType() {
      return PARSER;
    }

    public me.leoyuu.proto.BasePackets.PacketContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 seq = 1;</code>
     */
    int getSeq();

    /**
     * <code>optional int32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>optional string msg = 3;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .PacketType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .PacketType type = 4;</code>
     */
    me.leoyuu.proto.BasePackets.PacketType getType();

    /**
     * <code>optional .PacketContent content = 5;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .PacketContent content = 5;</code>
     */
    me.leoyuu.proto.BasePackets.PacketContent getContent();
    /**
     * <code>optional .PacketContent content = 5;</code>
     */
    me.leoyuu.proto.BasePackets.PacketContentOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Packet)
      PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      seq_ = 0;
      code_ = 0;
      msg_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              seq_ = input.readInt32();
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              me.leoyuu.proto.BasePackets.PacketContent.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(me.leoyuu.proto.BasePackets.PacketContent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.leoyuu.proto.BasePackets.internal_static_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.leoyuu.proto.BasePackets.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.leoyuu.proto.BasePackets.Packet.class, me.leoyuu.proto.BasePackets.Packet.Builder.class);
    }

    public static final int SEQ_FIELD_NUMBER = 1;
    private int seq_;
    /**
     * <code>optional int32 seq = 1;</code>
     */
    public int getSeq() {
      return seq_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>optional int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>optional .PacketType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .PacketType type = 4;</code>
     */
    public me.leoyuu.proto.BasePackets.PacketType getType() {
      me.leoyuu.proto.BasePackets.PacketType result = me.leoyuu.proto.BasePackets.PacketType.valueOf(type_);
      return result == null ? me.leoyuu.proto.BasePackets.PacketType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private me.leoyuu.proto.BasePackets.PacketContent content_;
    /**
     * <code>optional .PacketContent content = 5;</code>
     */
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <code>optional .PacketContent content = 5;</code>
     */
    public me.leoyuu.proto.BasePackets.PacketContent getContent() {
      return content_ == null ? me.leoyuu.proto.BasePackets.PacketContent.getDefaultInstance() : content_;
    }
    /**
     * <code>optional .PacketContent content = 5;</code>
     */
    public me.leoyuu.proto.BasePackets.PacketContentOrBuilder getContentOrBuilder() {
      return getContent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seq_ != 0) {
        output.writeInt32(1, seq_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
      }
      if (type_ != me.leoyuu.proto.BasePackets.PacketType.AppReverseMsg.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (content_ != null) {
        output.writeMessage(5, getContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seq_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
      }
      if (type_ != me.leoyuu.proto.BasePackets.PacketType.AppReverseMsg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getContent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.leoyuu.proto.BasePackets.Packet)) {
        return super.equals(obj);
      }
      me.leoyuu.proto.BasePackets.Packet other = (me.leoyuu.proto.BasePackets.Packet) obj;

      boolean result = true;
      result = result && (getSeq()
          == other.getSeq());
      result = result && (getCode()
          == other.getCode());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && type_ == other.type_;
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.leoyuu.proto.BasePackets.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.BasePackets.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.leoyuu.proto.BasePackets.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet)
        me.leoyuu.proto.BasePackets.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.leoyuu.proto.BasePackets.internal_static_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.leoyuu.proto.BasePackets.internal_static_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.leoyuu.proto.BasePackets.Packet.class, me.leoyuu.proto.BasePackets.Packet.Builder.class);
      }

      // Construct using me.leoyuu.proto.BasePackets.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seq_ = 0;

        code_ = 0;

        msg_ = "";

        type_ = 0;

        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.leoyuu.proto.BasePackets.internal_static_Packet_descriptor;
      }

      public me.leoyuu.proto.BasePackets.Packet getDefaultInstanceForType() {
        return me.leoyuu.proto.BasePackets.Packet.getDefaultInstance();
      }

      public me.leoyuu.proto.BasePackets.Packet build() {
        me.leoyuu.proto.BasePackets.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.leoyuu.proto.BasePackets.Packet buildPartial() {
        me.leoyuu.proto.BasePackets.Packet result = new me.leoyuu.proto.BasePackets.Packet(this);
        result.seq_ = seq_;
        result.code_ = code_;
        result.msg_ = msg_;
        result.type_ = type_;
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.leoyuu.proto.BasePackets.Packet) {
          return mergeFrom((me.leoyuu.proto.BasePackets.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.leoyuu.proto.BasePackets.Packet other) {
        if (other == me.leoyuu.proto.BasePackets.Packet.getDefaultInstance()) return this;
        if (other.getSeq() != 0) {
          setSeq(other.getSeq());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.leoyuu.proto.BasePackets.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.leoyuu.proto.BasePackets.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int seq_ ;
      /**
       * <code>optional int32 seq = 1;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>optional int32 seq = 1;</code>
       */
      public Builder setSeq(int value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 seq = 1;</code>
       */
      public Builder clearSeq() {
        
        seq_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .PacketType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .PacketType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .PacketType type = 4;</code>
       */
      public me.leoyuu.proto.BasePackets.PacketType getType() {
        me.leoyuu.proto.BasePackets.PacketType result = me.leoyuu.proto.BasePackets.PacketType.valueOf(type_);
        return result == null ? me.leoyuu.proto.BasePackets.PacketType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .PacketType type = 4;</code>
       */
      public Builder setType(me.leoyuu.proto.BasePackets.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .PacketType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private me.leoyuu.proto.BasePackets.PacketContent content_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.BasePackets.PacketContent, me.leoyuu.proto.BasePackets.PacketContent.Builder, me.leoyuu.proto.BasePackets.PacketContentOrBuilder> contentBuilder_;
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public me.leoyuu.proto.BasePackets.PacketContent getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? me.leoyuu.proto.BasePackets.PacketContent.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public Builder setContent(me.leoyuu.proto.BasePackets.PacketContent value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public Builder setContent(
          me.leoyuu.proto.BasePackets.PacketContent.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public Builder mergeContent(me.leoyuu.proto.BasePackets.PacketContent value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              me.leoyuu.proto.BasePackets.PacketContent.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public me.leoyuu.proto.BasePackets.PacketContent.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      public me.leoyuu.proto.BasePackets.PacketContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              me.leoyuu.proto.BasePackets.PacketContent.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>optional .PacketContent content = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.BasePackets.PacketContent, me.leoyuu.proto.BasePackets.PacketContent.Builder, me.leoyuu.proto.BasePackets.PacketContentOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.leoyuu.proto.BasePackets.PacketContent, me.leoyuu.proto.BasePackets.PacketContent.Builder, me.leoyuu.proto.BasePackets.PacketContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Packet)
    }

    // @@protoc_insertion_point(class_scope:Packet)
    private static final me.leoyuu.proto.BasePackets.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.leoyuu.proto.BasePackets.Packet();
    }

    public static me.leoyuu.proto.BasePackets.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public me.leoyuu.proto.BasePackets.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PacketContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PacketContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto\032\tsys.proto\032\nchat.proto\032\nuse" +
      "r.proto\"^\n\rPacketContent\022\027\n\006sysMsg\030\001 \001(\013" +
      "2\007.SysMsg\022\031\n\007chatMsg\030\002 \001(\0132\010.ChatMsg\022\031\n\007" +
      "userMsg\030\003 \001(\0132\010.UserMsg\"l\n\006Packet\022\013\n\003seq" +
      "\030\001 \001(\005\022\014\n\004code\030\002 \001(\005\022\013\n\003msg\030\003 \001(\t\022\031\n\004typ" +
      "e\030\004 \001(\0162\013.PacketType\022\037\n\007content\030\005 \001(\0132\016." +
      "PacketContent*Q\n\nPacketType\022\021\n\rAppRevers" +
      "eMsg\020\000\022\020\n\014AppSystemMsg\020\001\022\016\n\nAppChatMsg\020\002" +
      "\022\016\n\nAppUserMsg\020\003B\036\n\017me.leoyuu.protoB\013Bas" +
      "ePacketsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.leoyuu.proto.SystemPackets.getDescriptor(),
          me.leoyuu.proto.ChatPackets.getDescriptor(),
          me.leoyuu.proto.UserPackets.getDescriptor(),
        }, assigner);
    internal_static_PacketContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PacketContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PacketContent_descriptor,
        new java.lang.String[] { "SysMsg", "ChatMsg", "UserMsg", });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "Seq", "Code", "Msg", "Type", "Content", });
    me.leoyuu.proto.SystemPackets.getDescriptor();
    me.leoyuu.proto.ChatPackets.getDescriptor();
    me.leoyuu.proto.UserPackets.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
