// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sys.proto

package me.leoyuu.proto;

public final class SystemPackets {
  private SystemPackets() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code SysMsgType}
   */
  public enum SysMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SysReverseMsg = 0;</code>
     */
    SysReverseMsg(0),
    /**
     * <code>SysBindMsg = 1;</code>
     */
    SysBindMsg(1),
    /**
     * <code>SysBindRspMsg = 2;</code>
     */
    SysBindRspMsg(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SysReverseMsg = 0;</code>
     */
    public static final int SysReverseMsg_VALUE = 0;
    /**
     * <code>SysBindMsg = 1;</code>
     */
    public static final int SysBindMsg_VALUE = 1;
    /**
     * <code>SysBindRspMsg = 2;</code>
     */
    public static final int SysBindRspMsg_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SysMsgType valueOf(int value) {
      return forNumber(value);
    }

    public static SysMsgType forNumber(int value) {
      switch (value) {
        case 0: return SysReverseMsg;
        case 1: return SysBindMsg;
        case 2: return SysBindRspMsg;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SysMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SysMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SysMsgType>() {
            public SysMsgType findValueByNumber(int number) {
              return SysMsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return me.leoyuu.proto.SystemPackets.getDescriptor().getEnumTypes().get(0);
    }

    private static final SysMsgType[] VALUES = values();

    public static SysMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SysMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SysMsgType)
  }

  public interface SysBindOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SysBind)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>optional string sid = 2;</code>
     */
    java.lang.String getSid();
    /**
     * <code>optional string sid = 2;</code>
     */
    com.google.protobuf.ByteString
        getSidBytes();
  }
  /**
   * Protobuf type {@code SysBind}
   */
  public  static final class SysBind extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SysBind)
      SysBindOrBuilder {
    // Use SysBind.newBuilder() to construct.
    private SysBind(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysBind() {
      uid_ = 0;
      sid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SysBind(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysBind_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysBind_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.leoyuu.proto.SystemPackets.SysBind.class, me.leoyuu.proto.SystemPackets.SysBind.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int SID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sid_;
    /**
     * <code>optional string sid = 2;</code>
     */
    public java.lang.String getSid() {
      java.lang.Object ref = sid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSidBytes() {
      java.lang.Object ref = sid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (!getSidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (!getSidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.leoyuu.proto.SystemPackets.SysBind)) {
        return super.equals(obj);
      }
      me.leoyuu.proto.SystemPackets.SysBind other = (me.leoyuu.proto.SystemPackets.SysBind) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && getSid()
          .equals(other.getSid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysBind parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.leoyuu.proto.SystemPackets.SysBind prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SysBind}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SysBind)
        me.leoyuu.proto.SystemPackets.SysBindOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysBind_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysBind_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.leoyuu.proto.SystemPackets.SysBind.class, me.leoyuu.proto.SystemPackets.SysBind.Builder.class);
      }

      // Construct using me.leoyuu.proto.SystemPackets.SysBind.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        sid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysBind_descriptor;
      }

      public me.leoyuu.proto.SystemPackets.SysBind getDefaultInstanceForType() {
        return me.leoyuu.proto.SystemPackets.SysBind.getDefaultInstance();
      }

      public me.leoyuu.proto.SystemPackets.SysBind build() {
        me.leoyuu.proto.SystemPackets.SysBind result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.leoyuu.proto.SystemPackets.SysBind buildPartial() {
        me.leoyuu.proto.SystemPackets.SysBind result = new me.leoyuu.proto.SystemPackets.SysBind(this);
        result.uid_ = uid_;
        result.sid_ = sid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.leoyuu.proto.SystemPackets.SysBind) {
          return mergeFrom((me.leoyuu.proto.SystemPackets.SysBind)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.leoyuu.proto.SystemPackets.SysBind other) {
        if (other == me.leoyuu.proto.SystemPackets.SysBind.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (!other.getSid().isEmpty()) {
          sid_ = other.sid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.leoyuu.proto.SystemPackets.SysBind parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.leoyuu.proto.SystemPackets.SysBind) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sid_ = "";
      /**
       * <code>optional string sid = 2;</code>
       */
      public java.lang.String getSid() {
        java.lang.Object ref = sid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSidBytes() {
        java.lang.Object ref = sid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sid = 2;</code>
       */
      public Builder setSid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sid = 2;</code>
       */
      public Builder clearSid() {
        
        sid_ = getDefaultInstance().getSid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sid = 2;</code>
       */
      public Builder setSidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SysBind)
    }

    // @@protoc_insertion_point(class_scope:SysBind)
    private static final me.leoyuu.proto.SystemPackets.SysBind DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.leoyuu.proto.SystemPackets.SysBind();
    }

    public static me.leoyuu.proto.SystemPackets.SysBind getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysBind>
        PARSER = new com.google.protobuf.AbstractParser<SysBind>() {
      public SysBind parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SysBind(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysBind> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SysBind> getParserForType() {
      return PARSER;
    }

    public me.leoyuu.proto.SystemPackets.SysBind getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SysBindRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SysBindRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 heartBeatInterval = 1;</code>
     */
    int getHeartBeatInterval();
  }
  /**
   * Protobuf type {@code SysBindRsp}
   */
  public  static final class SysBindRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SysBindRsp)
      SysBindRspOrBuilder {
    // Use SysBindRsp.newBuilder() to construct.
    private SysBindRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysBindRsp() {
      heartBeatInterval_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SysBindRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              heartBeatInterval_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysBindRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysBindRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.leoyuu.proto.SystemPackets.SysBindRsp.class, me.leoyuu.proto.SystemPackets.SysBindRsp.Builder.class);
    }

    public static final int HEARTBEATINTERVAL_FIELD_NUMBER = 1;
    private int heartBeatInterval_;
    /**
     * <code>optional int32 heartBeatInterval = 1;</code>
     */
    public int getHeartBeatInterval() {
      return heartBeatInterval_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (heartBeatInterval_ != 0) {
        output.writeInt32(1, heartBeatInterval_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (heartBeatInterval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, heartBeatInterval_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.leoyuu.proto.SystemPackets.SysBindRsp)) {
        return super.equals(obj);
      }
      me.leoyuu.proto.SystemPackets.SysBindRsp other = (me.leoyuu.proto.SystemPackets.SysBindRsp) obj;

      boolean result = true;
      result = result && (getHeartBeatInterval()
          == other.getHeartBeatInterval());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HEARTBEATINTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getHeartBeatInterval();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysBindRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.leoyuu.proto.SystemPackets.SysBindRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SysBindRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SysBindRsp)
        me.leoyuu.proto.SystemPackets.SysBindRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysBindRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysBindRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.leoyuu.proto.SystemPackets.SysBindRsp.class, me.leoyuu.proto.SystemPackets.SysBindRsp.Builder.class);
      }

      // Construct using me.leoyuu.proto.SystemPackets.SysBindRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        heartBeatInterval_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysBindRsp_descriptor;
      }

      public me.leoyuu.proto.SystemPackets.SysBindRsp getDefaultInstanceForType() {
        return me.leoyuu.proto.SystemPackets.SysBindRsp.getDefaultInstance();
      }

      public me.leoyuu.proto.SystemPackets.SysBindRsp build() {
        me.leoyuu.proto.SystemPackets.SysBindRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.leoyuu.proto.SystemPackets.SysBindRsp buildPartial() {
        me.leoyuu.proto.SystemPackets.SysBindRsp result = new me.leoyuu.proto.SystemPackets.SysBindRsp(this);
        result.heartBeatInterval_ = heartBeatInterval_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.leoyuu.proto.SystemPackets.SysBindRsp) {
          return mergeFrom((me.leoyuu.proto.SystemPackets.SysBindRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.leoyuu.proto.SystemPackets.SysBindRsp other) {
        if (other == me.leoyuu.proto.SystemPackets.SysBindRsp.getDefaultInstance()) return this;
        if (other.getHeartBeatInterval() != 0) {
          setHeartBeatInterval(other.getHeartBeatInterval());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.leoyuu.proto.SystemPackets.SysBindRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.leoyuu.proto.SystemPackets.SysBindRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int heartBeatInterval_ ;
      /**
       * <code>optional int32 heartBeatInterval = 1;</code>
       */
      public int getHeartBeatInterval() {
        return heartBeatInterval_;
      }
      /**
       * <code>optional int32 heartBeatInterval = 1;</code>
       */
      public Builder setHeartBeatInterval(int value) {
        
        heartBeatInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 heartBeatInterval = 1;</code>
       */
      public Builder clearHeartBeatInterval() {
        
        heartBeatInterval_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SysBindRsp)
    }

    // @@protoc_insertion_point(class_scope:SysBindRsp)
    private static final me.leoyuu.proto.SystemPackets.SysBindRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.leoyuu.proto.SystemPackets.SysBindRsp();
    }

    public static me.leoyuu.proto.SystemPackets.SysBindRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysBindRsp>
        PARSER = new com.google.protobuf.AbstractParser<SysBindRsp>() {
      public SysBindRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SysBindRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysBindRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SysBindRsp> getParserForType() {
      return PARSER;
    }

    public me.leoyuu.proto.SystemPackets.SysBindRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SysMsgContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SysMsgContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .SysBind bind = 1;</code>
     */
    boolean hasBind();
    /**
     * <code>optional .SysBind bind = 1;</code>
     */
    me.leoyuu.proto.SystemPackets.SysBind getBind();
    /**
     * <code>optional .SysBind bind = 1;</code>
     */
    me.leoyuu.proto.SystemPackets.SysBindOrBuilder getBindOrBuilder();

    /**
     * <code>optional .SysBindRsp bindRsp = 2;</code>
     */
    boolean hasBindRsp();
    /**
     * <code>optional .SysBindRsp bindRsp = 2;</code>
     */
    me.leoyuu.proto.SystemPackets.SysBindRsp getBindRsp();
    /**
     * <code>optional .SysBindRsp bindRsp = 2;</code>
     */
    me.leoyuu.proto.SystemPackets.SysBindRspOrBuilder getBindRspOrBuilder();
  }
  /**
   * Protobuf type {@code SysMsgContent}
   */
  public  static final class SysMsgContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SysMsgContent)
      SysMsgContentOrBuilder {
    // Use SysMsgContent.newBuilder() to construct.
    private SysMsgContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysMsgContent() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SysMsgContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              me.leoyuu.proto.SystemPackets.SysBind.Builder subBuilder = null;
              if (bind_ != null) {
                subBuilder = bind_.toBuilder();
              }
              bind_ = input.readMessage(me.leoyuu.proto.SystemPackets.SysBind.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bind_);
                bind_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              me.leoyuu.proto.SystemPackets.SysBindRsp.Builder subBuilder = null;
              if (bindRsp_ != null) {
                subBuilder = bindRsp_.toBuilder();
              }
              bindRsp_ = input.readMessage(me.leoyuu.proto.SystemPackets.SysBindRsp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bindRsp_);
                bindRsp_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysMsgContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysMsgContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.leoyuu.proto.SystemPackets.SysMsgContent.class, me.leoyuu.proto.SystemPackets.SysMsgContent.Builder.class);
    }

    public static final int BIND_FIELD_NUMBER = 1;
    private me.leoyuu.proto.SystemPackets.SysBind bind_;
    /**
     * <code>optional .SysBind bind = 1;</code>
     */
    public boolean hasBind() {
      return bind_ != null;
    }
    /**
     * <code>optional .SysBind bind = 1;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysBind getBind() {
      return bind_ == null ? me.leoyuu.proto.SystemPackets.SysBind.getDefaultInstance() : bind_;
    }
    /**
     * <code>optional .SysBind bind = 1;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysBindOrBuilder getBindOrBuilder() {
      return getBind();
    }

    public static final int BINDRSP_FIELD_NUMBER = 2;
    private me.leoyuu.proto.SystemPackets.SysBindRsp bindRsp_;
    /**
     * <code>optional .SysBindRsp bindRsp = 2;</code>
     */
    public boolean hasBindRsp() {
      return bindRsp_ != null;
    }
    /**
     * <code>optional .SysBindRsp bindRsp = 2;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysBindRsp getBindRsp() {
      return bindRsp_ == null ? me.leoyuu.proto.SystemPackets.SysBindRsp.getDefaultInstance() : bindRsp_;
    }
    /**
     * <code>optional .SysBindRsp bindRsp = 2;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysBindRspOrBuilder getBindRspOrBuilder() {
      return getBindRsp();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bind_ != null) {
        output.writeMessage(1, getBind());
      }
      if (bindRsp_ != null) {
        output.writeMessage(2, getBindRsp());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bind_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBind());
      }
      if (bindRsp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBindRsp());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.leoyuu.proto.SystemPackets.SysMsgContent)) {
        return super.equals(obj);
      }
      me.leoyuu.proto.SystemPackets.SysMsgContent other = (me.leoyuu.proto.SystemPackets.SysMsgContent) obj;

      boolean result = true;
      result = result && (hasBind() == other.hasBind());
      if (hasBind()) {
        result = result && getBind()
            .equals(other.getBind());
      }
      result = result && (hasBindRsp() == other.hasBindRsp());
      if (hasBindRsp()) {
        result = result && getBindRsp()
            .equals(other.getBindRsp());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBind()) {
        hash = (37 * hash) + BIND_FIELD_NUMBER;
        hash = (53 * hash) + getBind().hashCode();
      }
      if (hasBindRsp()) {
        hash = (37 * hash) + BINDRSP_FIELD_NUMBER;
        hash = (53 * hash) + getBindRsp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsgContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.leoyuu.proto.SystemPackets.SysMsgContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SysMsgContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SysMsgContent)
        me.leoyuu.proto.SystemPackets.SysMsgContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysMsgContent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysMsgContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.leoyuu.proto.SystemPackets.SysMsgContent.class, me.leoyuu.proto.SystemPackets.SysMsgContent.Builder.class);
      }

      // Construct using me.leoyuu.proto.SystemPackets.SysMsgContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (bindBuilder_ == null) {
          bind_ = null;
        } else {
          bind_ = null;
          bindBuilder_ = null;
        }
        if (bindRspBuilder_ == null) {
          bindRsp_ = null;
        } else {
          bindRsp_ = null;
          bindRspBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysMsgContent_descriptor;
      }

      public me.leoyuu.proto.SystemPackets.SysMsgContent getDefaultInstanceForType() {
        return me.leoyuu.proto.SystemPackets.SysMsgContent.getDefaultInstance();
      }

      public me.leoyuu.proto.SystemPackets.SysMsgContent build() {
        me.leoyuu.proto.SystemPackets.SysMsgContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.leoyuu.proto.SystemPackets.SysMsgContent buildPartial() {
        me.leoyuu.proto.SystemPackets.SysMsgContent result = new me.leoyuu.proto.SystemPackets.SysMsgContent(this);
        if (bindBuilder_ == null) {
          result.bind_ = bind_;
        } else {
          result.bind_ = bindBuilder_.build();
        }
        if (bindRspBuilder_ == null) {
          result.bindRsp_ = bindRsp_;
        } else {
          result.bindRsp_ = bindRspBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.leoyuu.proto.SystemPackets.SysMsgContent) {
          return mergeFrom((me.leoyuu.proto.SystemPackets.SysMsgContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.leoyuu.proto.SystemPackets.SysMsgContent other) {
        if (other == me.leoyuu.proto.SystemPackets.SysMsgContent.getDefaultInstance()) return this;
        if (other.hasBind()) {
          mergeBind(other.getBind());
        }
        if (other.hasBindRsp()) {
          mergeBindRsp(other.getBindRsp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.leoyuu.proto.SystemPackets.SysMsgContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.leoyuu.proto.SystemPackets.SysMsgContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private me.leoyuu.proto.SystemPackets.SysBind bind_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysBind, me.leoyuu.proto.SystemPackets.SysBind.Builder, me.leoyuu.proto.SystemPackets.SysBindOrBuilder> bindBuilder_;
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public boolean hasBind() {
        return bindBuilder_ != null || bind_ != null;
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysBind getBind() {
        if (bindBuilder_ == null) {
          return bind_ == null ? me.leoyuu.proto.SystemPackets.SysBind.getDefaultInstance() : bind_;
        } else {
          return bindBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public Builder setBind(me.leoyuu.proto.SystemPackets.SysBind value) {
        if (bindBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bind_ = value;
          onChanged();
        } else {
          bindBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public Builder setBind(
          me.leoyuu.proto.SystemPackets.SysBind.Builder builderForValue) {
        if (bindBuilder_ == null) {
          bind_ = builderForValue.build();
          onChanged();
        } else {
          bindBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public Builder mergeBind(me.leoyuu.proto.SystemPackets.SysBind value) {
        if (bindBuilder_ == null) {
          if (bind_ != null) {
            bind_ =
              me.leoyuu.proto.SystemPackets.SysBind.newBuilder(bind_).mergeFrom(value).buildPartial();
          } else {
            bind_ = value;
          }
          onChanged();
        } else {
          bindBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public Builder clearBind() {
        if (bindBuilder_ == null) {
          bind_ = null;
          onChanged();
        } else {
          bind_ = null;
          bindBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysBind.Builder getBindBuilder() {
        
        onChanged();
        return getBindFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysBindOrBuilder getBindOrBuilder() {
        if (bindBuilder_ != null) {
          return bindBuilder_.getMessageOrBuilder();
        } else {
          return bind_ == null ?
              me.leoyuu.proto.SystemPackets.SysBind.getDefaultInstance() : bind_;
        }
      }
      /**
       * <code>optional .SysBind bind = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysBind, me.leoyuu.proto.SystemPackets.SysBind.Builder, me.leoyuu.proto.SystemPackets.SysBindOrBuilder> 
          getBindFieldBuilder() {
        if (bindBuilder_ == null) {
          bindBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.leoyuu.proto.SystemPackets.SysBind, me.leoyuu.proto.SystemPackets.SysBind.Builder, me.leoyuu.proto.SystemPackets.SysBindOrBuilder>(
                  getBind(),
                  getParentForChildren(),
                  isClean());
          bind_ = null;
        }
        return bindBuilder_;
      }

      private me.leoyuu.proto.SystemPackets.SysBindRsp bindRsp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysBindRsp, me.leoyuu.proto.SystemPackets.SysBindRsp.Builder, me.leoyuu.proto.SystemPackets.SysBindRspOrBuilder> bindRspBuilder_;
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public boolean hasBindRsp() {
        return bindRspBuilder_ != null || bindRsp_ != null;
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysBindRsp getBindRsp() {
        if (bindRspBuilder_ == null) {
          return bindRsp_ == null ? me.leoyuu.proto.SystemPackets.SysBindRsp.getDefaultInstance() : bindRsp_;
        } else {
          return bindRspBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public Builder setBindRsp(me.leoyuu.proto.SystemPackets.SysBindRsp value) {
        if (bindRspBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bindRsp_ = value;
          onChanged();
        } else {
          bindRspBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public Builder setBindRsp(
          me.leoyuu.proto.SystemPackets.SysBindRsp.Builder builderForValue) {
        if (bindRspBuilder_ == null) {
          bindRsp_ = builderForValue.build();
          onChanged();
        } else {
          bindRspBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public Builder mergeBindRsp(me.leoyuu.proto.SystemPackets.SysBindRsp value) {
        if (bindRspBuilder_ == null) {
          if (bindRsp_ != null) {
            bindRsp_ =
              me.leoyuu.proto.SystemPackets.SysBindRsp.newBuilder(bindRsp_).mergeFrom(value).buildPartial();
          } else {
            bindRsp_ = value;
          }
          onChanged();
        } else {
          bindRspBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public Builder clearBindRsp() {
        if (bindRspBuilder_ == null) {
          bindRsp_ = null;
          onChanged();
        } else {
          bindRsp_ = null;
          bindRspBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysBindRsp.Builder getBindRspBuilder() {
        
        onChanged();
        return getBindRspFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysBindRspOrBuilder getBindRspOrBuilder() {
        if (bindRspBuilder_ != null) {
          return bindRspBuilder_.getMessageOrBuilder();
        } else {
          return bindRsp_ == null ?
              me.leoyuu.proto.SystemPackets.SysBindRsp.getDefaultInstance() : bindRsp_;
        }
      }
      /**
       * <code>optional .SysBindRsp bindRsp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysBindRsp, me.leoyuu.proto.SystemPackets.SysBindRsp.Builder, me.leoyuu.proto.SystemPackets.SysBindRspOrBuilder> 
          getBindRspFieldBuilder() {
        if (bindRspBuilder_ == null) {
          bindRspBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.leoyuu.proto.SystemPackets.SysBindRsp, me.leoyuu.proto.SystemPackets.SysBindRsp.Builder, me.leoyuu.proto.SystemPackets.SysBindRspOrBuilder>(
                  getBindRsp(),
                  getParentForChildren(),
                  isClean());
          bindRsp_ = null;
        }
        return bindRspBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SysMsgContent)
    }

    // @@protoc_insertion_point(class_scope:SysMsgContent)
    private static final me.leoyuu.proto.SystemPackets.SysMsgContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.leoyuu.proto.SystemPackets.SysMsgContent();
    }

    public static me.leoyuu.proto.SystemPackets.SysMsgContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysMsgContent>
        PARSER = new com.google.protobuf.AbstractParser<SysMsgContent>() {
      public SysMsgContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SysMsgContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysMsgContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SysMsgContent> getParserForType() {
      return PARSER;
    }

    public me.leoyuu.proto.SystemPackets.SysMsgContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SysMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SysMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .SysMsgType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .SysMsgType type = 1;</code>
     */
    me.leoyuu.proto.SystemPackets.SysMsgType getType();

    /**
     * <code>optional .SysMsgContent content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .SysMsgContent content = 2;</code>
     */
    me.leoyuu.proto.SystemPackets.SysMsgContent getContent();
    /**
     * <code>optional .SysMsgContent content = 2;</code>
     */
    me.leoyuu.proto.SystemPackets.SysMsgContentOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code SysMsg}
   */
  public  static final class SysMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SysMsg)
      SysMsgOrBuilder {
    // Use SysMsg.newBuilder() to construct.
    private SysMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysMsg() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SysMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              me.leoyuu.proto.SystemPackets.SysMsgContent.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(me.leoyuu.proto.SystemPackets.SysMsgContent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.leoyuu.proto.SystemPackets.internal_static_SysMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.leoyuu.proto.SystemPackets.SysMsg.class, me.leoyuu.proto.SystemPackets.SysMsg.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .SysMsgType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .SysMsgType type = 1;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysMsgType getType() {
      me.leoyuu.proto.SystemPackets.SysMsgType result = me.leoyuu.proto.SystemPackets.SysMsgType.valueOf(type_);
      return result == null ? me.leoyuu.proto.SystemPackets.SysMsgType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private me.leoyuu.proto.SystemPackets.SysMsgContent content_;
    /**
     * <code>optional .SysMsgContent content = 2;</code>
     */
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <code>optional .SysMsgContent content = 2;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysMsgContent getContent() {
      return content_ == null ? me.leoyuu.proto.SystemPackets.SysMsgContent.getDefaultInstance() : content_;
    }
    /**
     * <code>optional .SysMsgContent content = 2;</code>
     */
    public me.leoyuu.proto.SystemPackets.SysMsgContentOrBuilder getContentOrBuilder() {
      return getContent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != me.leoyuu.proto.SystemPackets.SysMsgType.SysReverseMsg.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (content_ != null) {
        output.writeMessage(2, getContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != me.leoyuu.proto.SystemPackets.SysMsgType.SysReverseMsg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getContent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.leoyuu.proto.SystemPackets.SysMsg)) {
        return super.equals(obj);
      }
      me.leoyuu.proto.SystemPackets.SysMsg other = (me.leoyuu.proto.SystemPackets.SysMsg) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.leoyuu.proto.SystemPackets.SysMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.leoyuu.proto.SystemPackets.SysMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SysMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SysMsg)
        me.leoyuu.proto.SystemPackets.SysMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.leoyuu.proto.SystemPackets.SysMsg.class, me.leoyuu.proto.SystemPackets.SysMsg.Builder.class);
      }

      // Construct using me.leoyuu.proto.SystemPackets.SysMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.leoyuu.proto.SystemPackets.internal_static_SysMsg_descriptor;
      }

      public me.leoyuu.proto.SystemPackets.SysMsg getDefaultInstanceForType() {
        return me.leoyuu.proto.SystemPackets.SysMsg.getDefaultInstance();
      }

      public me.leoyuu.proto.SystemPackets.SysMsg build() {
        me.leoyuu.proto.SystemPackets.SysMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.leoyuu.proto.SystemPackets.SysMsg buildPartial() {
        me.leoyuu.proto.SystemPackets.SysMsg result = new me.leoyuu.proto.SystemPackets.SysMsg(this);
        result.type_ = type_;
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.leoyuu.proto.SystemPackets.SysMsg) {
          return mergeFrom((me.leoyuu.proto.SystemPackets.SysMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.leoyuu.proto.SystemPackets.SysMsg other) {
        if (other == me.leoyuu.proto.SystemPackets.SysMsg.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.leoyuu.proto.SystemPackets.SysMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.leoyuu.proto.SystemPackets.SysMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .SysMsgType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .SysMsgType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SysMsgType type = 1;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysMsgType getType() {
        me.leoyuu.proto.SystemPackets.SysMsgType result = me.leoyuu.proto.SystemPackets.SysMsgType.valueOf(type_);
        return result == null ? me.leoyuu.proto.SystemPackets.SysMsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .SysMsgType type = 1;</code>
       */
      public Builder setType(me.leoyuu.proto.SystemPackets.SysMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .SysMsgType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private me.leoyuu.proto.SystemPackets.SysMsgContent content_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysMsgContent, me.leoyuu.proto.SystemPackets.SysMsgContent.Builder, me.leoyuu.proto.SystemPackets.SysMsgContentOrBuilder> contentBuilder_;
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysMsgContent getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? me.leoyuu.proto.SystemPackets.SysMsgContent.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public Builder setContent(me.leoyuu.proto.SystemPackets.SysMsgContent value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public Builder setContent(
          me.leoyuu.proto.SystemPackets.SysMsgContent.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public Builder mergeContent(me.leoyuu.proto.SystemPackets.SysMsgContent value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              me.leoyuu.proto.SystemPackets.SysMsgContent.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysMsgContent.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      public me.leoyuu.proto.SystemPackets.SysMsgContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              me.leoyuu.proto.SystemPackets.SysMsgContent.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>optional .SysMsgContent content = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.leoyuu.proto.SystemPackets.SysMsgContent, me.leoyuu.proto.SystemPackets.SysMsgContent.Builder, me.leoyuu.proto.SystemPackets.SysMsgContentOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.leoyuu.proto.SystemPackets.SysMsgContent, me.leoyuu.proto.SystemPackets.SysMsgContent.Builder, me.leoyuu.proto.SystemPackets.SysMsgContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SysMsg)
    }

    // @@protoc_insertion_point(class_scope:SysMsg)
    private static final me.leoyuu.proto.SystemPackets.SysMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.leoyuu.proto.SystemPackets.SysMsg();
    }

    public static me.leoyuu.proto.SystemPackets.SysMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysMsg>
        PARSER = new com.google.protobuf.AbstractParser<SysMsg>() {
      public SysMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SysMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SysMsg> getParserForType() {
      return PARSER;
    }

    public me.leoyuu.proto.SystemPackets.SysMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SysBind_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SysBind_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SysBindRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SysBindRsp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SysMsgContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SysMsgContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SysMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SysMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsys.proto\"#\n\007SysBind\022\013\n\003uid\030\001 \001(\005\022\013\n\003s" +
      "id\030\002 \001(\t\"\'\n\nSysBindRsp\022\031\n\021heartBeatInter" +
      "val\030\001 \001(\005\"E\n\rSysMsgContent\022\026\n\004bind\030\001 \001(\013" +
      "2\010.SysBind\022\034\n\007bindRsp\030\002 \001(\0132\013.SysBindRsp" +
      "\"D\n\006SysMsg\022\031\n\004type\030\001 \001(\0162\013.SysMsgType\022\037\n" +
      "\007content\030\002 \001(\0132\016.SysMsgContent*B\n\nSysMsg" +
      "Type\022\021\n\rSysReverseMsg\020\000\022\016\n\nSysBindMsg\020\001\022" +
      "\021\n\rSysBindRspMsg\020\002B \n\017me.leoyuu.protoB\rS" +
      "ystemPacketsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SysBind_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SysBind_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SysBind_descriptor,
        new java.lang.String[] { "Uid", "Sid", });
    internal_static_SysBindRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SysBindRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SysBindRsp_descriptor,
        new java.lang.String[] { "HeartBeatInterval", });
    internal_static_SysMsgContent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SysMsgContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SysMsgContent_descriptor,
        new java.lang.String[] { "Bind", "BindRsp", });
    internal_static_SysMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SysMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SysMsg_descriptor,
        new java.lang.String[] { "Type", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
